# Generated by Django 4.2.3 on 2023-08-29 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0010_remove_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='mancb', to=settings.AUTH_USER_MODEL),
        ),
    ]
