# Generated by Django 4.2.3 on 2023-08-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreply',
            old_name='parent_comment',
            new_name='parent_reply',
        ),
    ]
